import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Loader2, Send, Zap } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

interface AIAssistantProps {
  onDesignGenerated: (design: Record<string, unknown>) => void;
}

export default function AIAssistant({ onDesignGenerated }: AIAssistantProps) {
  const [prompt, setPrompt] = useState("");
  const [model, setModel] = useState<"fast" | "smart">("smart");
  const [isLoading, setIsLoading] = useState(false);
  const [messages, setMessages] = useState<Array<{ role: string; content: string }>>([]);

  const handleSendPrompt = async () => {
    if (!prompt.trim()) return;

    setIsLoading(true);
    const userMessage = { role: "user", content: prompt };
    setMessages([...messages, userMessage]);

    try {
      // TODO: Call AI design API
      // For now, just simulate a response
      const aiResponse = {
        role: "assistant",
        content: `I'll help you design an ad with: "${prompt}". This feature will be powered by IO.NET models.`,
      };
      setMessages((prev) => [...prev, aiResponse]);
      setPrompt("");

      // Simulate design generation
      onDesignGenerated({
        headline: "Generated by AI",
        backgroundColor: "#1e293b",
        accentColor: "#f97316",
      });
    } catch (error) {
      console.error("AI request failed:", error);
      alert("Failed to generate design");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col h-full space-y-4">
      <div>
        <Label>Model</Label>
        <Select value={model} onValueChange={(v) => setModel(v as "fast" | "smart")}>
          <SelectTrigger>
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="fast">
              <span className="flex items-center gap-2">
                <Zap className="h-4 w-4" /> Fast (Quick changes)
              </span>
            </SelectItem>
            <SelectItem value="smart">
              <span className="flex items-center gap-2">
                <Zap className="h-4 w-4" /> Smart (Holistic design)
              </span>
            </SelectItem>
          </SelectContent>
        </Select>
      </div>

      {/* Chat History */}
      <div className="flex-1 overflow-y-auto space-y-3 bg-muted/50 p-3 rounded">
        {messages.length === 0 ? (
          <p className="text-sm text-muted-foreground text-center py-8">
            Describe what you want — the AI will design your ad.
          </p>
        ) : (
          messages.map((msg, idx) => (
            <div
              key={idx}
              className={`p-2 rounded text-sm ${
                msg.role === "user"
                  ? "bg-primary text-primary-foreground ml-4"
                  : "bg-background text-foreground mr-4"
              }`}
            >
              {msg.content}
            </div>
          ))
        )}
      </div>

      {/* Input */}
      <div className="flex gap-2">
        <Input
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="e.g. Dark background, add SALE badge, 3 columns"
          onKeyPress={(e) => e.key === "Enter" && handleSendPrompt()}
          disabled={isLoading}
        />
        <Button
          size="sm"
          onClick={handleSendPrompt}
          disabled={isLoading || !prompt.trim()}
        >
          {isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
        </Button>
      </div>

      <p className="text-xs text-muted-foreground">
        Powered by IO.NET AI models
      </p>
    </div>
  );
}
